### ISSUE TITLE
[Bug]: 加载新区块时高频卡死后崩溃

### ISSUE THREAD

**Issue by KiyooChan-hub** [MCModderAnchor/TACZ#277]
### 我已确认 ...

- [X] 我正在使用最新版的tacz
- [X] 无法在不安装tacz时复现

### Minecraft和模组加载器版本

forge 47.3.10

### tacz的版本

1.0.3

### Related Mods

```raw
无
```

### Description

表现为突然卡死后未响应，强制关进程后崩溃

### 复现步骤

在大量新区块加载时非常高发（大概率这时候炸），此外任意时候游玩均有可能复现卡死
任意复现方式的日志内容均一致

### 日志和崩溃报告

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: 
	Observable (observable), Version: 4.4.1
		Issue tracker URL: https://github.com/tasgon/observable/issues
		Mixin class: observable.mixin.ServerLevelMixin
		Target: net.minecraft.server.level.ServerLevel
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.redirect$emb000$observable$onTickBlock(ServerLevel.java:10155)

	Timeless & Classics Guns: Zero (tacz), Version: 1.0.3
		at TRANSFORMER/tacz@1.0.3/com.tacz.guns.entity.sync.core.SyncedEntityData.hasSyncedDataKey(SyncedEntityData.java:165)
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.rehash(Object2BooleanOpenHashMap.java:1304) ~[fastutil-8.5.9.jar%23129!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.insert(Object2BooleanOpenHashMap.java:249) ~[fastutil-8.5.9.jar%23129!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object2BooleanOpenHashMap.java:448) ~[fastutil-8.5.9.jar%23129!/:?] {}
	at com.tacz.guns.entity.sync.core.SyncedEntityData.hasSyncedDataKey(SyncedEntityData.java:165) ~[tacz-1.20.1-1.0.3-all.jar%23655!/:1.0.3] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.tacz.guns.event.SyncedEntityDataEvent.attachCapabilities(SyncedEntityDataEvent.java:29) ~[tacz-1.20.1-1.0.3-all.jar%23655!/:1.0.3] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.tacz.guns.event.__SyncedEntityDataEvent_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[tacz-1.20.1-1.0.3-all.jar%23655!/:1.0.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:623) ~[forge-1.20.1-47.3.10-universal.jar%23689!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin from mod modernfix,pl:mixin:A}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617) ~[forge-1.20.1-47.3.10-universal.jar%23689!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin from mod modernfix,pl:mixin:A}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.20.1-47.3.10-universal.jar%23689!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.20.1-47.3.10-universal.jar%23689!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.20.1-47.3.10-universal.jar%23689!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:265) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:cupboard.mixins.json:EntityLoadMixin from mod cupboard,pl:mixin:APP:create.mixins.json:EntityMixin from mod create,pl:mixin:APP:mixins.cardinal_components_entity.json:common.MixinEntity from mod cardinal_components_entity,pl:mixin:APP:forgematica.mixins.json:IMixinEntity from mod forgematica,pl:mixin:APP:balm.mixins.json:EntityMixin from mod balm,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin from mod supplementaries,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.EntityMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.misc.EntityMixin from mod servercore,pl:mixin:APP:curios.mixins.json:AccessorEntity from mod curios,pl:mixin:APP:fabric-entity-events-v1.mixins.json:EntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:convivium.mixins.json:EntityMixin from mod convivium,pl:mixin:APP:entityculling.mixins.json:CullableMixin from mod entityculling,pl:mixin:APP:backpacked.common.mixins.json:common.EntityMixin from mod backpacked,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:AttachmentTargetsMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:EntityMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity from mod bookshelf,pl:mixin:APP:entity_model_features-common.mixins.json:MixinEntity from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntity from mod entity_texture_features,pl:mixin:APP:wthit.mixins.json:EntityAccess from mod wthit,pl:mixin:APP:brewery-common.mixins.json:AlcoholPlayerMixin from mod brewery,pl:mixin:APP:refurbished_furniture.common.mixins.json:EntityAccessor from mod refurbished_furniture,pl:mixin:APP:refurbished_furniture.common.mixins.json:EntityMixin from mod refurbished_furniture,pl:mixin:APP:letmedespawn.mixins.json:EntityMixin from mod letmedespawn,pl:mixin:APP:mixins.fishnostuck.json:accessor.EntityAccessor from mod fishnostuck,pl:mixin:APP:nyfsspiders.mixins.json:EntityMixin from mod nyfsspiders,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin from mod kubejs,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin from mod create,pl:mixin:APP:create.mixins.json:accessor.EntityAccessor from mod create,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.entity.item.FallingBlockEntity.<init>(FallingBlockEntity.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:FallingBlockEntityMixin from mod supplementaries,pl:mixin:APP:crafttweaker.mixins.json:common.access.entity.AccessFallingBlockEntity from mod crafttweaker,pl:mixin:APP:architectury.mixins.json:MixinFallingBlockEntity from mod architectury,pl:mixin:APP:create.mixins.json:accessor.FallingBlockEntityAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.entity.item.FallingBlockEntity.<init>(FallingBlockEntity.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:FallingBlockEntityMixin from mod supplementaries,pl:mixin:APP:crafttweaker.mixins.json:common.access.entity.AccessFallingBlockEntity from mod crafttweaker,pl:mixin:APP:architectury.mixins.json:MixinFallingBlockEntity from mod architectury,pl:mixin:APP:create.mixins.json:accessor.FallingBlockEntityAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.entity.item.FallingBlockEntity.m_201971_(FallingBlockEntity.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:supplementaries-common.mixins.json:FallingBlockEntityMixin from mod supplementaries,pl:mixin:APP:crafttweaker.mixins.json:common.access.entity.AccessFallingBlockEntity from mod crafttweaker,pl:mixin:APP:architectury.mixins.json:MixinFallingBlockEntity from mod architectury,pl:mixin:APP:create.mixins.json:accessor.FallingBlockEntityAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.FallingBlock.m_213897_(FallingBlock.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior from mod oculus,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin from mod supplementaries,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin from mod starlight,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase from mod crafttweaker,pl:mixin:APP:copycats-common.mixins.json:foundation.copycat.BlockStateBaseMixin from mod copycats,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.redirect$emb000$observable$onTickBlock(ServerLevel.java:10155) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:mixins.cardinal_components_entity.json:common.MixinServerWorld from mod cardinal_components_entity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin from mod starlight,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:refurbished_furniture.common.mixins.json:ServerLevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:ServerLevelMixin from mod observable,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:680) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:mixins.cardinal_components_entity.json:common.MixinServerWorld from mod cardinal_components_entity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin from mod starlight,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:refurbished_furniture.common.mixins.json:ServerLevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:ServerLevelMixin from mod observable,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:forgematica.mixins.json:IMixinWorldTickScheduler from mod forgematica,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:forgematica.mixins.json:IMixinWorldTickScheduler from mod forgematica,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:mixins.cardinal_components_entity.json:common.MixinServerWorld from mod cardinal_components_entity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin from mod starlight,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:refurbished_furniture.common.mixins.json:ServerLevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:ServerLevelMixin from mod observable,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Kiyoo_Chan'/60, l='ServerLevel[Kiyo's World]', x=-2240.54, y=183.47, z=231.34]]
	Chunk stats: 6585
	Level dimension: minecraft:overworld
	Level spawn location: World: (62,148,297), Section: (at 14,4,9 in 3,9,18; chunk contains blocks 48,-64,288 to 63,319,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 459044 game time, 6000 day time
	Level name: Kiyo's World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin from mod pfm,pl:mixin:APP:fastquit.mixins.json:MinecraftServerAccessor from mod fastquit,pl:mixin:APP:fastquit.mixins.json:MinecraftServerMixin from mod fastquit,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin from mod pfm,pl:mixin:APP:fastquit.mixins.json:MinecraftServerAccessor from mod fastquit,pl:mixin:APP:fastquit.mixins.json:MinecraftServerMixin from mod fastquit,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:APP:forgematica.mixins.json:MixinIntegratedServer from mod forgematica,pl:mixin:APP:bobby.mixins.json:IntegratedServerMixin from mod bobby,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin from mod pfm,pl:mixin:APP:fastquit.mixins.json:MinecraftServerAccessor from mod fastquit,pl:mixin:APP:fastquit.mixins.json:MinecraftServerMixin from mod fastquit,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin from mod servercore,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin from mod pfm,pl:mixin:APP:fastquit.mixins.json:MinecraftServerAccessor from mod fastquit,pl:mixin:APP:fastquit.mixins.json:MinecraftServerMixin from mod fastquit,pl:mixin:APP:letmedespawn.mixins.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

**Comment by KiyooChan-hub** [comment]
补充：该bug仅在单机世界，或联机的客户端出现
联机服务端从未出现，推测是渲染层的问题

**Comment by xjqsh** [comment]
...不要把日志直接粘贴上来，要么传文件要么贴pastebin里面，你这样根本没法正常看，以及你装的模组属实是有点多，看堆栈信息怀疑存在模组冲突，请先按照说明以尽量少的模组复现问题，不然我们无从查起...
