### ISSUE TITLE
[ERROR] In console but everything works fine

### ISSUE THREAD

**Issue by DaDiGui** [MCModderAnchor/TACZ#50]
Hi, I'm getting this error and I don't know if it is serious or if it can affect the gameplay, although ingame everything works perfectly.

LOG: https://mclo.gs/Xu5zNni
Mod Version: **tacz-1.20.1-1.0.1-hotfix-release**

```
[15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.index.CommonAttachmentIndex.checkData(CommonAttachmentIndex.java:36)
--
93 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.index.CommonAttachmentIndex.getInstance(CommonAttachmentIndex.java:22)
94 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.loader.index.CommonAttachmentIndexLoader.loadAttachmentFromJsonString(CommonAttachmentIndexLoader.java:75)
95 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.loader.index.CommonAttachmentIndexLoader.loadAttachmentIndex(CommonAttachmentIndexLoader.java:47)
96 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.CommonGunPackLoader.readZipIndex(CommonGunPackLoader.java:186)
97 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.CommonGunPackLoader.readIndex(CommonGunPackLoader.java:165)
98 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.CommonGunPackLoader.reloadIndex(CommonGunPackLoader.java:83)
99 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.resource.DedicatedServerReloadManager.loadGunPack(DedicatedServerReloadManager.java:11)
100 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.event.CommonLoadPack.loadGunPack(CommonLoadPack.java:14)
101 | [15jun2024 13:20:50.419] [modloading-worker-0/ERROR] [STDERR/]: 	at TRANSFORMER/tacz@1.0.1-hotfix/com.tacz.guns.event.__CommonLoadPack_loadGunPack_FMLCommonSetupEvent.invoke(.dynamic)
```

**Comment by 3TUSK** [comment]
```
[15jun2024 13:20:50.325] [modloading-worker-0/WARN] [tacz/AttachmentDataLoader]: Failed to read data file: java.util.zip.ZipFile@7fa88529, entry: arip/attachments/data/laser.json

[15jun2024 13:20:50.419] [modloading-worker-0/WARN] [tacz/]: arip/attachments/index/laser_ogl.json index file read fail!
```

If you have 3rd party pack installed, you may want to check with them first.
