### ISSUE TITLE
Cant load into saved game, memory runs out but wont crash

### ISSUE THREAD

**Issue by Xplodin** [MCModderAnchor/TACZ#66]
```
Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.rehash(Object2BooleanOpenHashMap.java:1304) ~[fastutil-8.5.9.jar%23129!/:?]
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.insert(Object2BooleanOpenHashMap.java:249) ~[fastutil-8.5.9.jar%23129!/:?]
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.computeIfAbsent(Object2BooleanOpenHashMap.java:448) ~[fastutil-8.5.9.jar%23129!/:?]
	at com.tacz.guns.entity.sync.core.SyncedEntityData.hasSyncedDataKey(SyncedEntityData.java:165) ~[tacz-1.20.1-1.0.1-hotfix-release.jar%231320!/:1.0.1-hotfix]
	at com.tacz.guns.event.SyncedEntityDataEvent.attachCapabilities(SyncedEntityDataEvent.java:29) ~[tacz-1.20.1-1.0.1-hotfix-release.jar%231320!/:1.0.1-hotfix]
	at com.tacz.guns.event.__SyncedEntityDataEvent_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[tacz-1.20.1-1.0.1-hotfix-release.jar%231320!/:1.0.1-hotfix]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:623) ~[forge-1.20.1-47.2.19-universal.jar%231397!/:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617) ~[forge-1.20.1-47.2.19-universal.jar%231397!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.20.1-47.2.19-universal.jar%231397!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.20.1-47.2.19-universal.jar%231397!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.20.1-47.2.19-universal.jar%231397!/:?]
	at net.minecraft.world.entity.Entity.<init>(Entity.java:265) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:233) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.world.entity.Mob.<init>(Mob.java:123) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at artifacts.entity.MimicEntity.<init>(MimicEntity.java:38) ~[artifacts-forge-9.5.11.jar%23839!/:?]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6771_(ClientPacketListener.java:448) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:99) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:15) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_264308_(ClientPacketListener.java:2305) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:13) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.network.protocol.game.ClientboundBundlePacket.m_5797_(ClientboundBundlePacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231392!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

```

Heres the full debug.log

https://gist.github.com/Xplodin/43c9c810e63a7b8e6b152edde324ff78

**Comment by 286799714** [comment]
how to trigger this bug? more information is needed

**Comment by Xplodin** [comment]
I think this error is solved on my end, but to make it happen, I used a large modpack I created called Beanpack regurgitated
then I made a new world, save and quit, and then open the world again
